services:
  postgres_db:
    image: 'postgres:17'
    restart: unless-stopped
    networks:
      - dukarun_services_network
    environment:
      POSTGRES_DB: '${DB_NAME:-vendure}'
      POSTGRES_USER: '${DB_USERNAME:-vendure}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-vendure}'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USERNAME:-vendure} -d ${DB_NAME:-vendure}'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  timescaledb_audit:
    image: 'timescale/timescaledb:latest-pg17'
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - dukarun_services_network
    environment:
      POSTGRES_DB: '${AUDIT_DB_NAME:-audit_logs}'
      POSTGRES_USER: '${AUDIT_DB_USERNAME:-audit_user}'
      POSTGRES_PASSWORD: '${AUDIT_DB_PASSWORD:-audit_password}'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - 'timescaledb_audit_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${AUDIT_DB_USERNAME:-audit_user} -d ${AUDIT_DB_NAME:-audit_logs}'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  redis:
    image: 'redis:7-alpine'
    restart: unless-stopped
    networks:
      - dukarun_services_network
    command: "redis-server  --appendonly yes  --maxmemory 512mb  --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000\n"
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  dukarun_services_network:
    external: true
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  timescaledb_audit_data:
    driver: local
